name: timeline_editor
description: A flutter wiidget to help you manage timelines like video timeline with tracks editable or not. with move, actions...
version: 0.4.0-preview.1
homepage: https://github.com/neckaros/timeline_editor

environment:
  sdk: ">=2.18.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter
  linked_scroll_controller: ^0.2.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: